### ISSUE TITLE
Add typescript definitions

### ISSUE THREAD

**Issue by ibgreen** [visgl/luma.gl#1402]
### Background

Add typescript definitions (`d.ts`), start replacing https://www.npmjs.com/package/@danmarshall/deckgl-typings.

#### v8.4
- [ ] `@luma.gl/webgl` typings #1429 
- [ ] `@luma.gl/experimental` typings #1429 
- [ ] General typing improvements #1430
- [x] `@luma.gl/shadertools` typings #1426 
- [x] `@luma.gl/gltools` typings #1428 
- [x] Initial raw types port #1403

#### To Do List
  - [x] Add label and assign to milestone 
  - [ ] Coding
  - [ ] Doc update
  - [ ] Whats new update 
  - [ ] Test

**Comment by ibgreen** [comment]
@igorDykhta FYI
