### ISSUE TITLE
Tracker: 9.0 release

### ISSUE THREAD

**Issue by ibgreen** [visgl/luma.gl#1501]
# v9.0

## Bugs

https://github.com/visgl/luma.gl/issues?q=is%3Aissue+is%3Aopen+milestone%3A9.0.0

## Postponed

- [ ] **api guide** shaderlayout - probably needs a pass to align with latest API
- [ ] **api guide** bindings - likely needs a pass
- [ ] **engine** `BufferTransform` / `TextureTransform` docs - @donmccurdy 
- [ ] **engine** Model docs have never been good - arguably the most important page in the docs
- [ ] **gltf** `@luma.gl/gltf` module docs - @felixpalmer 

## Docs / Website

- [x] **api guide** rendering.md - duplicate information at the end. #1945 
- [x] **engine** AnimationLoop - contains a lot of old info
- [x] **engine** RenderLoop -> AnimationLoopTemplate + incorrect info
- [x] **core** Renderpipeline - contains GL constant references. @ibgreen #1945 
- [x] **core** texture docs - likely contain incorrect info towards the end @ibgreen #1945 

## Build

- [x] Fix ESM plugins 
- [x] New ocular esbuild 
- [x] Restore script build #1533
- [x] Fix `babel-inline-webgl-constants` Nice to have, not required for v9 - @donmccurdy  #1889  #1870  #1867 #1859
- [x] Fix `debug` module - @ibgreen 
- [x] Fix website -  @ibgreen 
- [x] Cherry-pick circular dependencies PR #1493 -  @ibgreen 
- [x] .ts files -  @ibgreen 

## API

- [x] WebGL 1 Removal - @ibgreen -#1933
- [x] glTF tracker @felixpalmer #1847
- [x] ShaderInputs @ibgreen 
- [x] Minimal `TextureTransform` port - @donmccurdy #1896 
- [x] Minimal `BufferTransform` port - @donmccurdy #1879 
- [x] Refactor: Drop `BufferWithAccessor` subclass  - @donmccurdy #1864
- [x] `CommandEncoder,copyTextureToBuffer()`: implement on webgl @donmccurdy 
- [x] Update all examples to use `UniformBuffer` - @ibgreen 
- [x] `UniformBuffer` support classes - @ibgreen 
- [x] `@luma.gl/gltf` - Restore glTF code and publish as separate module. - @felixpalmer 
- [x] Rename `luma.gl/gltools` to `luma.gl/webgl-legacy` - @ibgreen  (API - OpenJS Steering Committee Feedback)

Tests

- [x] Restore fp64 tests https://github.com/visgl/luma.gl/pull/1879 - @donmccurdy 

## Examples
- [x] Simplify tutorial gltf example and write tutorial page? - @felixpalmer -
- [x] Make WebGPU examples work again - @ibgreen - ShaderLayout refactor for deck.gl broke them
- [x] Fix example layout issue (should not take full screen)
- [x] Fix WebGL / WebGPU switcher in website @zbigg 
- [x] Fix example index page scrolling issue @zbigg 
- [x] New tutorial gltf example - @felixpalmer -

**Comment by ibgreen** [comment]
I think that PR is just moving the shader module file structure around. Those tests are most likely still commented out.

**Comment by donmccurdy** [comment]
I see – so these blocks?

https://github.com/visgl/luma.gl/blob/42a1c879c68ddc8c68e094df3af4f42cf791e3bf/modules/shadertools/test/modules-webgl1/fp64/fp64-arithmetic-transform.spec.ts#L77-L79

I'll take a look if no one is working on that already.

<details>
<summary>More links</summary>

- https://github.com/visgl/luma.gl/blob/42a1c879c68ddc8c68e094df3af4f42cf791e3bf/modules/shadertools/test/index.ts#L68-L71
- [`modules/shadertools/test/modules-webgl1/fp64/fp64-utils.spec.ts`](https://github.com/visgl/luma.gl/blob/master/modules/shadertools/test/modules-webgl1/fp64/fp64-utils.spec.ts)
- [`modules/shadertools/test/modules-webgl1/fp64/fp64-arithmetic-transform.spec.ts`](https://github.com/visgl/luma.gl/blob/master/modules/shadertools/test/modules-webgl1/fp64/fp64-arithmetic-transform.spec.ts)

</details>

**Comment by donmccurdy** [comment]
>  CommandEncoder: encapsulate webgl readPixel()`

@ibgreen I've restored tests for copyTextureToBuffer in #1885, that seems to be working, is anything else required for this task?

**Comment by ibgreen** [comment]
> > CommandEncoder: encapsulate webgl readPixel()`
> 
> @ibgreen I've restored tests for copyTextureToBuffer in #1885, that seems to be working, is anything else required for this task?

Ultimately the reason we did this is to make applications perform texture reads through a portable API. Right now apps (and deck.gl) have to import `webgl` module. See e.g. https://github.com/visgl/luma.gl/blob/master/examples/showcase/instancing/app.ts#L6

You could try and see if it is not too hard to replace all use of readPixels, but then again we don't necessarily need to solve this completely in 9.0, we could come back to this in 9.1. 

Still, it is good to have this enabler in place!
