### ISSUE TITLE
v9 GLTF issue tracker

### ISSUE THREAD

**Issue by felixpalmer** [visgl/luma.gl#1847]
Task list for GLTF support in v9

#### To Do List
  - [ ] Initial implementation https://github.com/visgl/luma.gl/pull/1819
  - [ ] Release gltf package on npm
  - [ ] Update website/package.json with gltf dependency
  - [ ] gltf bounding box courtesy method
  - [ ] Extract `gltf-instantiator` to function
  - [ ] More tests
  - [ ] Remove GLTF attribute name mapping in `GPUGeometry`
  - [ ] Upgrade guide mention GLTF

**Comment by ibgreen** [comment]
We used to have a showcase example for gltf (currently in examples-wip folder) that did create IBL lighting. @felixpalmer create a new simpler glTF tutorial example

I didn't confirm that IBL didn't work but it required cube textures and I think those are broken right now.

**Comment by felixpalmer** [comment]
@chrisgervang @ibgreen I've added a task to the list above to include IBL. I have it as lower priority as my primary objective is getting something rendering in deck so we can port the layers that depend on GLTF

**Comment by ibgreen** [comment]
Makes sense, I suggest we save our effort and fix this after the texture refactor in #1860 lands.
