### ISSUE TITLE
v9.1 Tracker

### ISSUE THREAD

**Issue by ibgreen** [visgl/luma.gl#1946]
# These tasks can be postponed to v9.1 - not critical for deck.gl v9.0

### Documentation
- [ ] **tutorials** - need to be ported to v9 (currently marked as outdated

### Code
- [ ] Support for "struct / array" uniform type decls in shader modules (for multiple lights in lighting module).
- [ ] Refactor: Simplify `Texture` class - @ibgreen 
- [ ] Fix fp64 under Apple M1 #1764 -  @donmccurdy 
- [ ] `Transform` code needs to be platform "independent". Pending potential new Transform API - @Pessimistress  
- [ ] ` make `readPixels*()` portable and move webgl -> core module - @donmccurdy 
- [ ] Restore all render tests (update golden images?) - @Pessimistress 
- [ ] Port all classic webgl test suites to adapter classes (Copy tests from webgl-legacy into api-tests) - Is this required for v9 @ibgreen?
- [ ] Fix `api/cubemap` example -  - Wait till texture refactor lands?
- [ ] Fix `api/texture-3d` example -  - Wait till texture refactor lands?
- [ ] Fix DOF example? - **P2**- Currently uses custom uniform buffer and custom post processing code. Rewrite as standard example.
- [ ] Restore original glTF example (environment lighting etc) 
- [ ] Restore loaders.gl glTF example 
- [ ] Restore glfx example (so that we can test / showcase postprocessing modules) - **P2** - TBD
