### ISSUE TITLE
Tracker: luma.gl v9.2

### ISSUE THREAD

**Issue by ibgreen** [visgl/luma.gl#2263]
*Note: Work continues in luma.gl v9.3 tracker.*

Goal: Production WebGPU support
- Target Date: Q2 2025 - "fast follow" to [v9.1](https://github.com/visgl/luma.gl/issues/1946) and [v9.0](https://github.com/visgl/luma.gl/issues/1501)

#### Docs / Website

https://github.com/visgl/luma.gl/issues/2407

- [ ] All examples run on WebGPU
- [ ] Documentation improvements (TBD)

#### Tests
- [ ] Restore all luma.gl render tests (update golden images?) - **P2** - @Pessimistress ?
- [ ] Tests: Port all classic webgl test suites to core classes - **P2**

#### Deprecations
- [ ] Remove `Model.updateModuleSettings`.
- [ ] Remove `device.setGLParameters` & Co
- [ ] ...

#### Bugs

- [ ] https://github.com/visgl/luma.gl/issues?q=is%3Aissue+is%3Aopen+milestone%3Av9.2
- [ ] https://github.com/visgl/luma.gl/issues?q=is%3Aissue+is%3Aopen+milestone%3Av9.1

#### General
- [x] TypeScript v5.7, all `"strict"` TypeScript options are now applied to all luma.gl modules.
- [x] Website tooling upgrades
- [x] Improved GitHub issue templates

#### Modules

**@luma.gl/core**

- [x] `Texture` class refactors completed.
- [x] Orthogonalized `CommandEncoder`/`CommandBuffer` API  @ibgreen 

**@luma.gl/webgl**

- [x] Remove webgl-texture-utils.ts **P0**

**@luma.gl/webgpu**

- [x] Add WebGPU validation code to all Device Resource classes **P2**
