### ISSUE TITLE
Tracker: v6.0 Attribute Handling Refactor Follow-up

### ISSUE THREAD

**Issue by ibgreen** [visgl/luma.gl#572]
#### Background 

Tracker issue for various additional work stemming from the changes and refactors in v6.0. The various tasks are expected to be spread out across 6.x releases.

#### Optimize Uniform  Settings

- [ ] `Program`: Create separate function to bind texture units. Call before each draw call (possibly optionally).
- [x] `Program`: Stop setting all uniforms before each draw call.
- [x] `Program`: Restore & improve uniform diffing to avoid resetting uniforms.
- [ ] `Program`: Investigate letting app specify texture units for textures. And set texture units directly. To make luma cover intended use of texture units.

#### UniformBlock support

- [ ] `Program`: Handle uniform block indices like texture units described above.
- [ ] `ProgramConfiguration`: Add support for uniform blocks

#### VertexArray

- [x] `VertexArray`: Add option to "unbind" to avoid conflicts with TransformFeedback.
- [x] `VertexArray`: Investigate using "only bind during use"  to cover WebGL1 instead of Khronos polyfill? to save on bundle size and complexity

#### To Do List 
  - [ ] Add label and assign to milestone 
  - [ ] Coding
  - [ ] Doc update
  - [ ] Whats new update 
  - [ ] Test

**Comment by tsherif** [comment]
@ibgreen is this still relevant?

**Comment by ibgreen** [comment]
It could be worth going through this together, and then you can make the decision.
