### ISSUE TITLE
Tracker: glTF Support

### ISSUE THREAD

**Issue by ibgreen** [visgl/luma.gl#702]
## v7.2/7.3 Documented glTF API and loaders.gl integration

See discussion in #1150

- [ ] Documented API for "loading" glTF files.
- [ ] Easy way to create a scenegraph from a url
- [ ] Figure out how to map animations, multiple scenegraphs etc.
- [ ] Update examples in deck.gl and loaders.gl

## v8.x Standards compliant glTF support

- [ ] Support full animation system, weights, joints, skins etc.
- [ ] Further Scenegraph Refinements (Frustum Culling, Depth Sorting, Geometry-based Picking...)
- [ ] Support for Cameras
- [ ] Support for glTF Light extension [KHR_lights_punctual](https://github.com/KhronosGroup/glTF/tree/master/extensions/2.0/Khronos/KHR_lights_punctual)

- [ ] Separate `Model` from `Scenegraph`
- [ ] Add `Mesh` node to Scenegraph that can hold a Model (@ibgreen/@georgios-uber)
- [ ] Implement Composite Geometry support in `Mesh` P2 (@ibgreen/@georgios-uber)

- [ ] See also #979 for transpiler improvements that would help glTF (transpile main shader)

## v7.0 Experimental/partial glTF Support

- [x] Doc updates (New classes / What's New)
- [x] Interoperability testing (test with more glTF models)
- [x] Integrate PBR Rendering with Lighting System (@georgios-uber)
- [x] Implement PBR rendering based on Material System (@georgios-uber)
- [x] Implement Extensible Material System (@jianhuang01)
- [x] Test, debug, fix `glTFInstantiator` against the Khronos reference models (@georgios-uber)
- [x] Basic `glTFInstantiator` class that maps loaded glTG tree to luma scenegraph (@ibgreen, @georgios-uber)
- [x] Improved support for interleaved attributes (Add `Accessor.buffer` field) (@ibgreen) #869
- [x] Add a parser for glTF formatted files, building on existing GLBLoader (in loaders.gl)
- [x] Support non-GLTF models (e.g. meshes/scenegraphs from loaders.gl)
- [x] RFC
