### ISSUE TITLE
Tracker: @luma.gl/debug module

### ISSUE THREAD

**Issue by Pessimistress** [visgl/luma.gl#727]
#### Background 

Tools to enable easier testing and debugging of luma.gl models.

### v7.1
- [ ] Display IndexType in debug table (#681)
- [ ] Save debug info in gl context #550
- [ ] Refactor debug support #148
- [ ] Probe setting for controlling debug activation (remove programmatic flags)
- [ ] Doc update
- [ ] Whats new update
- [ ] Test

### v7.0
- [x] Finalize `glsl-to-js` transpiler
- [x] Move WebGL debug dependency to debug module #818 
- [x] Move `makeDebugContext` to debug module #822

### v6.3
- [x] Create separate @luma.gl/debug module

**Comment by Pessimistress** [comment]
https://github.com/uber/luma.gl/pull/722

https://github.com/uber/luma.gl/pull/726
