### ISSUE TITLE
Tracker: Lighting

### ISSUE THREAD

**Issue by ibgreen** [visgl/luma.gl#947]
Tracker for lighting improvements

## IDEAS
- [ ] luma.gl - Add example that uses `PhongLighting` (Modify shadowmap example?)
- [ ] Proposal - Support `lights` option (single array of lights) in addition to/instead of lightSettings
- [ ] Rename light settings module (`ligthing` => `lightSettings`)? 

## v8.3
- [ ] Add support for PBR unlit property (glTF KHR_unlit extension) See https://github.com/visgl/deck.gl/issues/3705

## v7.0
- [ ] Developer Guide `lighting.md` (NEW) - Explain that we have two lighting models and three light types. (@georgios-uber)
- [ ] See if we can redefine light classes so that we do not need to redefine them in deck.gl
- [x] Audit light classes and light parameters (user friendly API).
- [x] Update `phongLighting` to use `lightSettings`
- [x] luma.gl example that uses PBR lighting (glTF example)
- [x] pbr module integration with lightSettings (@georgios-uber)
- [x] `lighting` module, break out from `phongLighting` (@ibgreen) 
- [x] Rename `lighting` module as `lightSettings` (@ibgreen) 
- [x] `phongLighting` module (@jianhuang01)
