### ISSUE TITLE
Tracker: Shadertools

### ISSUE THREAD

**Issue by ibgreen** [visgl/luma.gl#979]
## v7.1 Shader Composition
- [x] Dynamic shader composition (#1071)

## v8.x
- [ ] Consider: Using less regex and more defines
- [ ] Allow shader-modules to specify the version of GLSL they export
- [ ] Add ability to transpile main shader code

**Comment by tgorkin** [comment]
Potentially combine with #969

**Comment by ibgreen** [comment]
These are two quite separate modules, doesn't really make sense to track them together.

The Tracker tasks are typically more carefully set up, do not expect there to be much overlap.
